### ISSUE TITLE
[OSS] Finish React app, react-app

### ISSUE THREAD

**Issue by kellishouts** [AirshipCMS/react-app.airshipcms.io#1]
Below is the content from the old Jira ticket, though it may not be the most up-to-date. The docs already in the angular-1 and angular babel projects are more up-to-date.

---

_This project has already been started. Jon used create-react-app because it sets up a lot of things. However, it's not the easiest to configure once ejected._

### Summary
This demo project demonstrates an Airship project that uses a React SPA to render all pages.

### Subdomain
react-app.airshipcms.io
This site exists, and you have been added as a superadmin.

### Github
clone this down, you may work off branches and make PRs to merge to master. master is still in the wip state.  https://github.com/AirshipCMS/react-app.airshipcms.io

### SPA Routes
{code}[{"pattern":"/.*","destination":"/"}]{code}
(this is already set up)

### Build Tools
create-react-app (webpack + babel + postcss)

### Templating
pull down the project to see template structure.

### Functionality
this part has not yet been implemented, so build out the app

### Schema (same as other repos)
- Root:  Main page that launches the SPA
- Styling (page)
- Airship Schema (page)
- React Tutorial (page)
the contents describe how the spa app was setup after landing, implementation details, gulp configuration, and the local dev cycle to create and launch this project (tutorial)
- Elements (collection)
For the collection index.html listing page, use react to iterate over the elements to only show thumbnail and name. clicking on one element should go to it's detail page (*still in spa*) that shows all the information.

### Routes
The spa should have the following routes:
- **/** : landing page, `GET /api/pages/__root__` displays root page fields
- **/airship-schema** : airship-schema
- **/styling** : styling tutorial page, `GET /api/pages/styling`, displays body
- **/react-tutorial** : react tutorial page, `GET /api/pages/react-tutorial`, displays body
- **/elements** : elements collection page, `GET /api/pages/elements`, displays list of links to each element
- **/elements/:permalink** : example aerostat detail, `GET /api/collection/elements/view/:permalink`, displays the element fields according to layout

Inside the spa, have some navigation.
Inside the spa, the title and github link in the header are also rendered by the SPA.

A visitor to this Airship Site should be able to use this project and the github repo as a working example of how to create a spa app that uses create-react-app using AirshipCMS as the CMS.

*Note: If it is better to start over again with just react, babel and webpack then we don't have to use create-react-app.*

### Styling
Like the Angular projects except blue theme (see mockup)

### Bounty
**$150** for completion of the above.
If edits are needed after initial review, yet the scope is completed, additional tasks for revisions will be created.

**Comment by kellishouts** [comment]
Update the verbiage for this project based on the Angular-1 Repo & add the appropriate assets and cms-content directories with markdown files. Note that the logo is different (blue for react).
Add Syntax Highlighting.
Finish this Project Example.
This may be easier to do now, since _any_ assets can go into the assets directory, and things no longer need to be in /assets/scripts, /assets/styles, and /assets/media.

**Comment by kellishouts** [comment]
These are the react logos if you don't have them:
[Archive.zip](https://github.com/AirshipCMS/react-app.airshipcms.io/files/1171711/Archive.zip)

And the React Theme was blue. Layout, if you don't already have it:
![react theme](https://user-images.githubusercontent.com/1865400/28552277-1f4ae32a-7089-11e7-9d99-ac610c387a66.png)

**Comment by fobabett** [comment]
starting

**Comment by fobabett** [comment]
done
